### PR TITLE
Added jsx support

### PR DESCRIPTION
**Pull request by Ekatwikz**
Simple `.jsx` format,  
assuming `.jsx` means React (usually does)

### CODE REVIEW

**Review by zpiatt — COMMENTED** [review]
Change gen_jsx to:
```
gen_jsx() {
cat << EOF
import React from 'react';
function ${FILENAME#.*}() {
  return (
    <>
    </>
  );
}
export default ${FILENAME#.*};
EOF
}
```

**Comment by zpiatt** [comment]
Please refer to: https://wiki.bash-hackers.org/syntax/pe regarding parameter expansions.

**Comment by Ekatwikz** [comment]
I'm not sure if I'm misunderstanding the correction
Assume for example I want to `gen` a file in a specific existing directory, eg: `/f/o/o/bar.jsx`
I want the function name to simply be `bar`.

If I take `${FILENAME#.*}`, won't I be removing only an initial substring of `.*` from the path?
The idea I was using was to remove all the "\*/" chunks from the beginning (for directories), then a single ".\*" chunk from the end (for the extension)

The proposal doesn't seem to work on my shell rn

**Comment by zpiatt** [comment]
You're right, sorry lost in the sauce at work right now and got confused. There still must be a better way, I'll have to think about when I can have on my attention on it.

**Comment by zpiatt** [comment]
Slightly cleaner and should work for `/f/o/o/bar.jsx`. 
```
gen_jsx() {
BASENAME_NO_EXT="${FILENAME##*/}"
cat << EOF
import React from 'react';
function ${BASENAME_NO_EXT%.*}() {
  return (
    <>
    </>
  );
}
export default ${BASENAME_NO_EXT%.*};
EOF
}
```

**Comment by Ekatwikz** [comment]
> Slightly cleaner and should work for `/f/o/o/bar.jsx`.
> 
> ```
> gen_jsx() {
> BASENAME_NO_EXT="${FILENAME##*/}"
> cat << EOF
> import React from 'react';
> function ${BASENAME_NO_EXT%.*}() {
>   return (
>     <>
>     </>
>   );
> }
> export default ${BASENAME_NO_EXT%.*};
> EOF
> }
> ```

Np, [d047ae0](https://github.com/membersincewayback/gen/pull/14/commits/d047ae0) now uses this syntax

**Comment by zpiatt** [comment]
Still needs quotes: `BASENAME_NO_EXT="${FILENAME##*/}"`. I run shellcheck on the command line to help me with this stuff. It's really hard to keep track of the bashisms in your head.

**Comment by Ekatwikz** [comment]
> Still needs quotes: `BASENAME_NO_EXT="${FILENAME##*/}"`. I run shellcheck on the command line to help me with this stuff. It's really hard to keep track of the bashisms in your head.

I just installed it :sweat_smile: , this one comes out clean with shellcheck though, should I still quote it?

**Comment by zpiatt** [comment]
I'm sticking with "Quote everything" from the contribution guidelines I stole from Neofetch. Once I merge this I'm going to fix the quotes on the get_args function.

**Review by zpiatt — APPROVED** [review]

**Pull request merged**
