### PR TITLE
Add templates support

### PR DESCRIPTION
**Pull request by tmiland**
- Added support for templates

Script will look for templates in: `templates/template.ext` Simply add a template in the current folder and run `gen file.ext`

Had to reset, didn't see the new commits and got lost in the conflicts. :yum:

### CODE REVIEW

**Comment by tmiland** [comment]
To test this, run `git clone https://github.com/natelandau/shell-scripting-templates.git templates` in a temporary folder, and do `gen test.sh`

**Comment by zpiatt** [comment]
I think I stepped on your commit again. Also I'm getting permission denied trying to clone your repo.

**Comment by tmiland** [comment]
> I think I stepped on your commit again. Also I'm getting permission denied trying to clone your repo.

Updated link to https, it was ssh for the repo.

**Comment by zpiatt** [comment]
`zac@fedora-server:~/tommy/templates
$ ls
LICENSE  README.md  sedfiles  template.sh  template_standalone.sh  test  utilities
zac@fedora-server:~/tommy/templates
$ gen test.sh
chmod: cannot access 'ext=bash': No such file or directory
`

**Comment by tmiland** [comment]
So, with any of the arguments, the template isn't included, which would be correct i think according to the logic of the script.

Templates are only included running `gen filename.ext`

**Comment by tmiland** [comment]
> `zac@fedora-server:~/tommy/templates $ ls LICENSE README.md sedfiles template.sh template_standalone.sh test utilities zac@fedora-server:~/tommy/templates $ gen test.sh chmod: cannot access 'ext=bash': No such file or directory `

Yeah, i pushed a fix for the missing `;`

**Comment by zpiatt** [comment]
Do you have Discord? Maybe you could explain what I'm missing here... this is when you find out I'm a sysadmin and not a software engineer!

**Comment by zpiatt** [comment]
https://discord.gg/rDdHfCud

**Comment by tmiland** [comment]
> Do you have Discord? Maybe you could explain what I'm missing here... this is when you find out I'm a sysadmin and not a software engineer!

Well, the templates folder you cloned, should be in a subfolder in your current folder, you tried to `gen` in the templates folder. :smile: 

So do `cd ..` and `gen test.sh`

Edit:
And change on line 344 in template.sh to 

```
_sourceUtilities_ "$(_findBaseDir_)/templates/utilities"
```

**Comment by zpiatt** [comment]
I think we could get the templates to echo into the existing functions if they exist instead of  adding the entire else block.

**Comment by tmiland** [comment]
> I think we could get the templates to echo into the existing functions if they exist instead of adding the entire else block.

That was what i originally did, but the issue was that you need to remove the hardcoded template from the provided template,
or else it would be doubled at the top, which isn't ideal if using lots of different templates.

**Comment by zpiatt** [comment]
We could probably add a return if ${template} and avoid this like I did with quiet. I'm going to merge for now since I think we're on the same page as to what we want.

**Comment by tmiland** [comment]
> We could probably add a return if ${template} and avoid this like I did with quiet. I'm going to merge for now since I think we're on the same page as to what we want.

I have one more fix.

**Comment by zpiatt** [comment]
Have you had a chance to see that latest method for template integration? I had to remove your use of cat and echo, and changed the method of assigned EXT to be more portable. I have an idea to expand templates even further and slightly more seamlessly but wanted to see what you thought so far.

**Pull request merged**
